version: '1.1'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: x156856663
      MYSQL_DATABASE: Prueba
      MYSQL_USER: bulaciac
      MYSQL_PASSWORD: x156856663
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: bulaciac
      PMA_PASSWORD: x156856663

volumes:
  mysql_data:
